parser:
  pdf:
    file_size_limit: 100
    max_page_limit: 100
    max_token_limit: 100000
    max_worker: 10
    ppt_page_title_score_weight: [0.7, 0.3]
    layout_label:
      title_senior_mode: false
      enable_mode: close   # 是否使用layout模型进行版面分析、文本过滤、文档树结构解析，sci_paper/all/close
      model_path: "model/layout.onnx"
      model_score_th: 0.9
      overlap_ratio_th: 0.8
  pptx:
    file_size_limit: 100
    max_page_limit: 1000
    max_shapes_limit: 5000
    ppt_page_title_score_weight: [ 0.7, 0.3 ]
  html:
    file_size_limit: 100
    max_token_limit: 200000
  txt:
    file_size_limit: 100
  md:
    file_size_limit: 100
    max_token_limit: 1000000
  xlsx:
    file_size_limit: 100
    max_1st_col_char: 200
    max_2nd_col_char: 5000
    max_row_limit: 50000
    col_limit: 2
  docx:
    file_size_limit: 100
    large_table_rows: 100
    max_large_table_limit: 5
    max_table_rows_limit: 500
    max_paragraph_limit: 5000
    max_token_limit: 100000
splitter:
  is_need_segment: true
  type: "punc"
  target_length: 850
  overlap_ratio: 0.2
  en_segment_puncs: '\n|\. |\?|!|,|;'
  zh_segment_puncs: '\n|。|？|！|】|；|，| '
extractor:
  is_add_metadata: true
  is_extracted_summary_chunk: true
  is_generated_summary_chunk: false
  local_llm_path: "model/chatglm3-6b/"
  model_type: "chatglm3"
  prompt_type: "structure"
  device: "cuda:0"
index:
  #各系统字段和业务字段的映射关系，mapping字典必须是全集，包括chunk_info_id、chunk_info、inverted、semantic、scalar_filter
  mapping:
    DOC_ID: "doc_id"
    CHUNK_ID: "chunk_id"
    CONTENT: "content"
    TITLE: "title"
    CHAPTER_SUMMARY: "chapter_summary"
    CHUNK: "chunk"
    KNOWLEDGE_BASE_NAME: "user_id"
    SESSION_ID: "session_id"
  chunk_info_id: "chunk_id" #正排信息id（往ES插入的时候该字段作为es中的正排信息id），服务化相关配置
  chunk_info: [ "doc_id","chunk_id","content","title","chapter_summary","chunk","user_id","session_id" ] #正排信息字段
  inverted: [ "content","doc_id","user_id","session_id" ] #获取bm25信息字段，即倒排字段
  semantic: [ "content" ] # 1.用于获取embedding信息字段，即向量字段。2.用于构建向量引擎的打分字段
  scalar_filter: [ "doc_id","user_id","session_id" ] #向量引擎中标量过滤字段

degrade:
  enable: true
embedding:
  url: http://10.50.91.124:6510/cal
  # 每个请求语义服务batch包含的chunk数量
  batch_size: 16
  # 单个文档chunks截断长度,degrade.enable=true时，该参数生效
  truncate_num: 100
  # 最大重试次数
  max_retry: 3
  # 超时时间（s）
  timeout: 3

tw:
  url: http://10.50.91.124:8895/get_tw
  # 访问词权重服务的线程数量
  thread_nums: 4
  # 单个文档chunks截断长度,degrade.enable=true时，该参数生效
  truncate_num: 100
  # 最大重试次数
  max_retry: 3
  # 超时时间（s）
  timeout: 3

es:
  url: http://10.50.91.195:9200
  analyzer: poisson_jieba_search
  index: ikun-dev
  bm25:
    # 单个文档chunks截断长度,degrade.enable=true时，该参数生效
    truncate_num: 100
    # 最大重试次数
    max_retry: 3
    # 超时时间（s）
    timeout: 3
  export:
    timeout: 100

vs:
  url: 10.50.91.124:9010
