es_short_term:
  url: http://10.168.12.121:9200
  analyzer: poisson_jieba_search
  index: short_term_jieer 
  # index: short_term_xiaoneng

es_long_term:
  url: http://10.168.12.121:9200
  analyzer: poisson_jieba_search
  index: long_term_offline

es_ug_mock:
  url: http://10.168.12.121:9200
  analyzer: poisson_jieba_search
  index: ug_mock

meta_engine:
  url: http://10.50.91.196:9171/search
  
faiss_engine:  
  vision_cache: data/image_cache
  index: faiss_index.index

event_caption_engine:
  index_path: data/event_caption