splitter:
  is_need_segment: true
  type: "punc"
  target_length: 850
  overlap_ratio: 0.2
  en_segment_puncs: '\n|\. |\?|!|,|;'
  zh_segment_puncs: '\n|。|？|！|】|；|，| '
extractor:
  is_add_metadata: true
  is_extracted_summary_chunk: true
  is_generated_summary_chunk: false
  target_length: 4000

degrade:
  enable: true
embedding:
  # 单个文档chunks截断长度
  truncate_num: 100

tw:
  # 单个文档chunks截断长度
  truncate_num: 100

es:
  bm25:
    # 单个文档chunks截断长度
    truncate_num: 100
