# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import vector_service_pb2 as vector__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vector_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class VectorWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/proto.VectorWorker/SayHello',
                request_serializer=vector__service__pb2.HelloRequest.SerializeToString,
                response_deserializer=vector__service__pb2.HelloReply.FromString,
                _registered_method=True)
        self.VectorBinaryInit = channel.unary_unary(
                '/proto.VectorWorker/VectorBinaryInit',
                request_serializer=vector__service__pb2.VectorBinaryInitRequest.SerializeToString,
                response_deserializer=vector__service__pb2.VectorBinaryInitResponse.FromString,
                _registered_method=True)
        self.VectorBinaryReloadIndex = channel.unary_unary(
                '/proto.VectorWorker/VectorBinaryReloadIndex',
                request_serializer=vector__service__pb2.VectorBinaryReloadIndexRequest.SerializeToString,
                response_deserializer=vector__service__pb2.VectorBinaryReloadIndexResponse.FromString,
                _registered_method=True)
        self.DeleteIndex = channel.unary_unary(
                '/proto.VectorWorker/DeleteIndex',
                request_serializer=vector__service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=vector__service__pb2.DeleteReply.FromString,
                _registered_method=True)
        self.BatchQuery = channel.unary_unary(
                '/proto.VectorWorker/BatchQuery',
                request_serializer=vector__service__pb2.BatchRequest.SerializeToString,
                response_deserializer=vector__service__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.FQuery = channel.unary_unary(
                '/proto.VectorWorker/FQuery',
                request_serializer=vector__service__pb2.FQRequest.SerializeToString,
                response_deserializer=vector__service__pb2.FQResponse.FromString,
                _registered_method=True)
        self.GetIndexInfo = channel.unary_unary(
                '/proto.VectorWorker/GetIndexInfo',
                request_serializer=vector__service__pb2.GetIndexInfoRequest.SerializeToString,
                response_deserializer=vector__service__pb2.GetIndexInfoResponse.FromString,
                _registered_method=True)
        self.GetVectorDocs = channel.unary_unary(
                '/proto.VectorWorker/GetVectorDocs',
                request_serializer=vector__service__pb2.GetVectorDocsRequest.SerializeToString,
                response_deserializer=vector__service__pb2.GetVectorDocsResponse.FromString,
                _registered_method=True)
        self.CreateVectorIndex = channel.unary_unary(
                '/proto.VectorWorker/CreateVectorIndex',
                request_serializer=vector__service__pb2.CreateVectorIndexRequest.SerializeToString,
                response_deserializer=vector__service__pb2.CreateVectorIndexResponse.FromString,
                _registered_method=True)
        self.GetNodeInfo = channel.unary_unary(
                '/proto.VectorWorker/GetNodeInfo',
                request_serializer=vector__service__pb2.NodeInfoRequest.SerializeToString,
                response_deserializer=vector__service__pb2.NodeInfoResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/proto.VectorWorker/Flush',
                request_serializer=vector__service__pb2.FlushRequest.SerializeToString,
                response_deserializer=vector__service__pb2.FlushResponse.FromString,
                _registered_method=True)
        self.DeleteDocsByIds = channel.unary_unary(
                '/proto.VectorWorker/DeleteDocsByIds',
                request_serializer=vector__service__pb2.DeleteByIdsRequest.SerializeToString,
                response_deserializer=vector__service__pb2.DeleteByIdsResponse.FromString,
                _registered_method=True)
        self.UpsertDocs = channel.unary_unary(
                '/proto.VectorWorker/UpsertDocs',
                request_serializer=vector__service__pb2.InsertOrUpdateRequest.SerializeToString,
                response_deserializer=vector__service__pb2.InsertOrUpdateResponse.FromString,
                _registered_method=True)


class VectorWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorBinaryInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorBinaryReloadIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorDocs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVectorIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertDocs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=vector__service__pb2.HelloRequest.FromString,
                    response_serializer=vector__service__pb2.HelloReply.SerializeToString,
            ),
            'VectorBinaryInit': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorBinaryInit,
                    request_deserializer=vector__service__pb2.VectorBinaryInitRequest.FromString,
                    response_serializer=vector__service__pb2.VectorBinaryInitResponse.SerializeToString,
            ),
            'VectorBinaryReloadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorBinaryReloadIndex,
                    request_deserializer=vector__service__pb2.VectorBinaryReloadIndexRequest.FromString,
                    response_serializer=vector__service__pb2.VectorBinaryReloadIndexResponse.SerializeToString,
            ),
            'DeleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIndex,
                    request_deserializer=vector__service__pb2.DeleteRequest.FromString,
                    response_serializer=vector__service__pb2.DeleteReply.SerializeToString,
            ),
            'BatchQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchQuery,
                    request_deserializer=vector__service__pb2.BatchRequest.FromString,
                    response_serializer=vector__service__pb2.BatchResponse.SerializeToString,
            ),
            'FQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.FQuery,
                    request_deserializer=vector__service__pb2.FQRequest.FromString,
                    response_serializer=vector__service__pb2.FQResponse.SerializeToString,
            ),
            'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexInfo,
                    request_deserializer=vector__service__pb2.GetIndexInfoRequest.FromString,
                    response_serializer=vector__service__pb2.GetIndexInfoResponse.SerializeToString,
            ),
            'GetVectorDocs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorDocs,
                    request_deserializer=vector__service__pb2.GetVectorDocsRequest.FromString,
                    response_serializer=vector__service__pb2.GetVectorDocsResponse.SerializeToString,
            ),
            'CreateVectorIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVectorIndex,
                    request_deserializer=vector__service__pb2.CreateVectorIndexRequest.FromString,
                    response_serializer=vector__service__pb2.CreateVectorIndexResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=vector__service__pb2.NodeInfoRequest.FromString,
                    response_serializer=vector__service__pb2.NodeInfoResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=vector__service__pb2.FlushRequest.FromString,
                    response_serializer=vector__service__pb2.FlushResponse.SerializeToString,
            ),
            'DeleteDocsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocsByIds,
                    request_deserializer=vector__service__pb2.DeleteByIdsRequest.FromString,
                    response_serializer=vector__service__pb2.DeleteByIdsResponse.SerializeToString,
            ),
            'UpsertDocs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertDocs,
                    request_deserializer=vector__service__pb2.InsertOrUpdateRequest.FromString,
                    response_serializer=vector__service__pb2.InsertOrUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.VectorWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.VectorWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/SayHello',
            vector__service__pb2.HelloRequest.SerializeToString,
            vector__service__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorBinaryInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/VectorBinaryInit',
            vector__service__pb2.VectorBinaryInitRequest.SerializeToString,
            vector__service__pb2.VectorBinaryInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorBinaryReloadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/VectorBinaryReloadIndex',
            vector__service__pb2.VectorBinaryReloadIndexRequest.SerializeToString,
            vector__service__pb2.VectorBinaryReloadIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/DeleteIndex',
            vector__service__pb2.DeleteRequest.SerializeToString,
            vector__service__pb2.DeleteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/BatchQuery',
            vector__service__pb2.BatchRequest.SerializeToString,
            vector__service__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/FQuery',
            vector__service__pb2.FQRequest.SerializeToString,
            vector__service__pb2.FQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/GetIndexInfo',
            vector__service__pb2.GetIndexInfoRequest.SerializeToString,
            vector__service__pb2.GetIndexInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorDocs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/GetVectorDocs',
            vector__service__pb2.GetVectorDocsRequest.SerializeToString,
            vector__service__pb2.GetVectorDocsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVectorIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/CreateVectorIndex',
            vector__service__pb2.CreateVectorIndexRequest.SerializeToString,
            vector__service__pb2.CreateVectorIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/GetNodeInfo',
            vector__service__pb2.NodeInfoRequest.SerializeToString,
            vector__service__pb2.NodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/Flush',
            vector__service__pb2.FlushRequest.SerializeToString,
            vector__service__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/DeleteDocsByIds',
            vector__service__pb2.DeleteByIdsRequest.SerializeToString,
            vector__service__pb2.DeleteByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertDocs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.VectorWorker/UpsertDocs',
            vector__service__pb2.InsertOrUpdateRequest.SerializeToString,
            vector__service__pb2.InsertOrUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
